Documentation:
  Enabled: false
LineLength:
  Max: 99
require: rubocop-rails
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
