Documentation:
  Enabled: false
LineLength:
  Max: 99
require: rubocop-rails
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/models/*.rb'