Documentation:
  Enabled: false
LineLength:
  Max: 100
require: rubocop-rails
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
