default: &default
  open_library_url: "https://openlibrary.org/api/books?bibkeys=ISBN:"
  open_library_suffix: "&format=json&jscmd=data"

development:
  <<: *default
  secret_key_base: 76fc1319f39a5f5f6bb9a016bf9957300f73cb02fe48ff6942f275df48cad71184fdf3d8116c769782161abfcfc5f50e4cd521d8cf674910d36f685bfc327d93
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_authentication: <%= ENV["MAILER_AUTHENTICATION"] %>

test:
  <<: *default
  secret_key_base: 15063970c9d57c9495fa4c087847b0714a5908f81703000f6c20688214ed1ba417894071a00abae6abf22298d8722c904910d03b8eb84ff3f1d951b9d9c4d462

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
